export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const REQUEST_WORKOUTS = 'REQUEST_WORKOUTS';
export const RECEIVE_WORKOUTS = 'RECEIVE_WORKOUTS';